version: "3.7"

services:
  app:
    build: .
    image: nestjs-project-template:nestjs-project-template
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3308:3306

  redis:
    image: redis
    ports:
      - 6381:6379
