version: '3.7'

services:
  app:
    build: .
    image: nestjs-project-template:nestjs-project-template
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    # command: yarn start:dev
    # volumes:
    #   - .:/root/nestjs-project-template

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - 6381:6379

volumes:
  db_data:
