export enum ERROR_CODE {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INACTIVE_USER = 'INACTIVE_USER',
  TERMINATED_USER = 'TERMINATED_USER',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  TOO_MANY_REQUESTS = 'Too Many Requests',
  TOO_MANY_REQUESTS_TO_RECEIVE_OTP = 'TOO_MANY_REQUESTS_TO_RECEIVE_OTP',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  INVALID_EMAIL_ADDRESS = 'INVALID_EMAIL_ADDRESS',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INVALID_OTP = 'INVALID_OTP',

  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_DECODED_ACCESS_TOKEN = 'INVALID_DECODED_ACCESS_TOKEN',
}
