export const TEMPLATE = {
  CODE: {
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    TWO_FACTOR_AUTHENTICATION: 'TWO_FACTOR_AUTHENTICATION',
  },
  KEYWORDS: {
    FORGOT_PASSWORD: {
      USERNAME: '{{{USERNAME}}}',
      NEW_PASSWORD: '{{{NEW_PASSWORD}}}',
    },
    TWO_FACTOR_AUTHENTICATION: {
      USERNAME: '{{{USERNAME}}}',
      OTP: '{{{OTP}}}',
      OTP_TTL: '{{{OTP_TTL}}}',
    },
  },
};
