export const TEMPLATE = {
  CODE: {
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    TWO_FACTOR_AUTHENTICATION: 'TWO_FACTOR_AUTHENTICATION',
  },
  KEYWORDS: {
    FORGOT_PASSWORD: {
      TEMPORARY_PASSWORD: '{{TEMPORARY_PASSWORD}}',
    },
    TWO_FACTOR_AUTHENTICATION: {
      OTP: '{{OTP}}',
      OTP_TIME_TO_LIVE: '{{OTP_TIME_TO_LIVE}}',
    },
  },
};
